### ISSUE TITLE
Card does not get detected.

### ISSUE THREAD

**Issue by sriranjanr** [ljos/MFRC522#10]
Hello,

I am using the RC522 and arduino 1.6.5 and also tried with 1.6.4. I checked the connections atleast 10 times and it does not detect the card. Please tell me what to do.

Ranjan
![output rfid 1](https://cloud.githubusercontent.com/assets/8640547/17831000/7a665bb0-66fb-11e6-8008-41ed41b3604b.jpg)

**Comment by ljos** [comment]
I don't think I am able to help you; it doesn't seem like you are using this library.
