### ISSUE TITLE
How to check if card is removed or not?

### ISSUE THREAD

**Issue by AmitParmar2005** [ljos/MFRC522#15]
Hi,

I am not sure if this is considered as an issue or not but I looked on internet and tried different solutions for 2 days and couldn't find any satisfactory result. 

Can somebody please help me to find solution of the problem I am facing? I need to detect somehow if card is removed from RFID device.

In other RFID library (link given below), they found a solution for the problem i am facing. I applied same method here but Its not working.

https://github.com/miguelbalboa/rfid/issues/188

Thanks and Regards,
Amit

**Comment by ljos** [comment]
You should be able to rewrite the same code that is presented in that issue to use the api from this library. If you are not able to do that I suggest you use that library instead and the code that is listed in that issue.

**Comment by AmitParmar2005** [comment]
Thanks for your reply.

I already tried the same method here but It didnt work. Let me try once again. May be I missed something.

Thanks Again.

**Comment by ljos** [comment]
If you can provide an example of what you are trying and what you have tried/think is wrong I can try to help you more, but as you can see from the latest commit: I haven't worked on this for a while.
