### ISSUE TITLE
CRC error

### ISSUE THREAD

**Issue by e4awais** [ljos/MFRC522#6]
how to clear a crc error when it occurs ? 

a soft/hard reset does not solve the problem.

**Comment by ljos** [comment]
The CRCErr should clear when you run a new command. If you remove power and add it back, does the self-test pass?

**Comment by e4awais** [comment]
thanks ... 

there is yet another inquiry ... how do i read an unauthenticated card just once like an authenticated one ? 

at present it keeps reading the unauthenticated card. 

thanks

**Comment by ljos** [comment]
I am not completely sure what you are asking, but example code in the repo is built in a way to just continue looping and reading any card in the vicinity.

**Comment by e4awais** [comment]
thanks ...
