### ISSUE TITLE
Error in haltTag()

### ISSUE THREAD

**Issue by tonywestonuk** [ljos/MFRC522#9]
Turning off encryption *MUST* happen after the command has been sent.   Because of this the card is never halted...... this is what is causing the same card to be read over and over again in the example  #program.

Please note that if the card is halted, the status returned will be ERR - the card it halted and so can  not respond. so a timeout will occur.  In this instance, this is the correct response.

I have reversed the commands, and it works as intended.

// Send command before turning off encryption.
  status = commandTag(MFRC522_TRANSCEIVE, buffer, 4, buffer, &len);

  clearBitMask(Status2Reg, 0x08);  // turn off encryption

**Comment by ljos** [comment]
Thank you for looking into this.
